baseURL = "https://flexpaksc.netlify.com/"
languageCode = "en-us"
title = "FlexPak SC"
theme = "hugo-serif-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Experienced package consultant"
    meta_og_title = "FlexPak-SC"
    meta_og_type = "website"
    meta_og_url = "https://flexpaksc.netlify.com"
    meta_og_image = "{{ .Site.BaseURL }}/flexpaksc.png"
    meta_og_description = "Packaging Sales Consultant"
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

#[[menu.main]]
#	name = "Services"
#	url = "/services/"
#    weight = 1

[[menu.main]]
    name = "About Us"
    url = "/team/"
    weight = 2

#[[menu.main]]
#	name = "Testimonials"
#	url = "/testimonials/"
#	weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
